### ISSUE TITLE
Bring pom plugin versions up to date

### ISSUE THREAD

**Issue by dellgreen** [jtidy/jtidy#10]
Bring pom plugins up to date so they don't get stuck on obsolete versions, or versions that wont work under newer jdks

**Comment by wltjr** [comment]
I made some other minor changes to pom.xml. Updated URLs I had updated to the other location under my company name. I dropped the developers section. I do not feel that is necessary or beneficial, just clutters up file. Just a heads up.

**Comment by wltjr** [comment]
This one I never touched, I just did dependencies. I am not to familiar with the plugins.
