### ISSUE TITLE
Become root of all forks or detach from other forks

### ISSUE THREAD

**Issue by wltjr** [jtidy/jtidy#11]
Pretty minor and moot for now. For the long term for contributor commits to count on their contribution charts. We either need to either detach from other forks, and/or become the root fork. Those are the 2 available routes.

1. Get permission from the original root fork owner @spullara to replace them as the root fork.
    Need to contact Github once we get @spullara permission to re-root.

2. Detach from other forks and become a stand alone repo.
    Also requires contacting Github to request such. Lose relation to other forks/repos.

At some point one of those two needs to take place. Ideally # 1 as that would keep association with other forks. Though that is not really necessary. The main goal is to have commits/contributions show on peoples contribution charts. Also to not be seen as a fork, but the main project for others to contribute. Rather than a bunch of forks with different modifications spread all over the place. Just an attempt to clean house and keep project relation to other forks.

**Comment by spullara** [comment]
Ha, I had no idea that I had become the root fork for other contributions. Happy to help!

**Comment by wltjr** [comment]
@spullara yeah it happens. Someone grabs code for their needs, another sees it and so on. I also sent you an invite to join in this project. Since we do have some of your changes/commits. I grabbed the bottom most fork to fork from to get alls modifications. I also sent all downstream forks between this one and yours invites as well.

Anyway with you being the root. If you could send a request/email to Github requesting that this become the root fork. They can make the changes, just need your permission. Regular contact form should be more than suffice. Beyond that please feel free to join in and help along with what ever you feel like or nothing at all. No worries either way.

Thanks for your willingness to help!

**Comment by spullara** [comment]
I send them a request via the contact form.

**Comment by wltjr** [comment]
Excellent, thank you!

**Comment by wltjr** [comment]
@spullara thanks much they took care of it! Much appreciated! Feel free to contribute in any way you like. @dellgreen is doing most of the work. I am mostly here for support and cheer leading, less the outfit and pom poms.
