### ISSUE TITLE
Keep or drop ant build.xml, switch to gradle from maven

### ISSUE THREAD

**Issue by wltjr** [jtidy/jtidy#13]
Not sure if it makes sense to keep 2 build systems. Not sure any time will be spent on the ant build.xml. Maybe need to remove that. I do not believe there is any benefit to maintaining 2 build systems. Most will likely go with maven for dependencies etc.

Along those same lines, could also switch to gradle from maven. That is pretty moot to me, but is worth considering if making changes to build system etc. I have no preference either way. Though for new projects I tend to go with Gradle vs Maven, because the configuration/build files tend to be smaller, build.gradle vs pom.xml. But that also maybe more work than worth while. Just mentioning it for discussion, since visiting build systems for the project.

**Comment by dellgreen** [comment]
I would be happy to move to gradle as that's my primary build system, I rarely use maven and moved away from xml based build systems years ago

**Comment by wltjr** [comment]
I have no problems with moving to Gradle. Not sure if that is easier to maintain than Maven. I think most are moving towards the Gradle route. I think we are in agreeance at least to drop ant. I think that may have been kept for when maven was new and for transition. Not sure ant was ever meant to be kept long term.

**Comment by wltjr** [comment]
The only issue with Gradle is for like Travis and maybe Shippable as well, likely have to install Gradle vs using system. The version of Gradle by default in at least Travis has issues with Java 9. Gradle [failed to build](https://travis-ci.org/Obsidian-StudiosInc/jtsys/jobs/345071016) another small project of mine under Java 9.

Not a big deal, just have to download a copy as part of Travis builds vs using installed. That would add a tiny bit of additional time to builds to fetch/unpack Gradle. Just something to keep in mind. Not a reason to remain with Maven. But maven is easier from that perspective.

Mostly comes down to time to maintain/update pom.xml vs time to migrate to gradle. Which ever requires the least amount of time I would assume.

**Comment by dellgreen** [comment]
another option is to include the gradle jar as part of the repo, this is what we do for all our jobs at work to keep them self contained

**Comment by wltjr** [comment]
I am not really big on putting binaries or other in repos. Just a personal preference. I even stopped adding gradle wrappers. Just another thing to maintain. Bit easier to update versions via a number in say travis.yml. I grab [gradle] (https://github.com/Obsidian-StudiosInc/solitaire/blob/master/.travis.yml#L26) for an android app I need to update. Its not to much.

I am good either way, I build this using an abnormal build system in Gentoo. Outside of the CI builds not sure I will be building it much myself. So I would proceed how ever you like. It can always be changed later if needed. That is more internal that would effect other contributors and what not. Most will likely grab from maven/gradle repos and never build directly...

**Comment by dellgreen** [comment]
no that's fine, as its a github project, i'd imagine there is an expectation that dependencies will be pulled  remotely and not included locally

**Comment by wltjr** [comment]
Its really up to each project. I do think good practice is to not include such. I think it also makes maintaining things easier. You just have versions in 2 files, the build system and ci files. When I go to like release, I increment versions there and tag. Its a good place for versions for dependencies as well as build system. Like in that past example, I can just update the version number of Gradle, as part of regular package release/version updating. I think that is less effort than downloading and committing a binary, but likely moot. I just try to avoid binaries in repos. Though in some private ones I do have some. Either way, its more if you or another wants to make the effort to switch to gradle vs update/tweak the maven. I can update the CI stuff if things are switched to gradle.
