### ISSUE TITLE
Re-write history to associate past committers with their github accounts

### ISSUE THREAD

**Issue by wltjr** [jtidy/jtidy#14]
The following committers have accounts on github, but their commits are not linked. Ideally they add the email addresses used for those commits to their github accounts.

@aditsu @fgiust and @steffenyount

Short of them adding emails to their account. The other option is to re-write history so we can update the author and match them to their accounts that way. Its pretty moot, but would be ideal to match the commits to the authors that have accounts on github. If they see this and add emails themselves, there is nothing to be done here. But if they do not act, someone may need to re-write history and force push. Which will effect all others, as they will need to force pull. A one time thing, hopefully can be avoided, but maybe necessary someday.

**Comment by wltjr** [comment]
Since this has become the root of others forks, probably not a good idea to re-write history. This can remain open to see if others want to add their old Sourge Forge emails. I had to do that sometime back for my old wltjr@gentoo.org email, that is no longer in use. It does not need to be validated.

Its all pretty moot just would be nice to link past commits in the repo to the respective peoples accounts on Github. No other purpose other than that.

**Comment by aditsu** [comment]
Hi, what email address would you like me to add to my github account?
My commits seem to appear as aditsu@<some guid>

**Comment by wltjr** [comment]
I thought it was your old S.F. email, but seems that was not preserved. Likely moot now without re-writing history and updating authors that way. No worries, I will likely close this. I got your email and will reply to that ASAP.

**Comment by haumacher** [comment]
History rewrite is not an option.
