### ISSUE TITLE
Can't load the scm provider. No such provider: 'git@github.com'

### ISSUE THREAD

**Issue by dellgreen** [jtidy/jtidy#16]
When running the 'site' goal the following error is produced

ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project jtidy: Error during page generation: Error rendering Maven report: Cannot run changelog command : Can't load the scm provider. No such provider: 'git@github.com'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wltjr** [comment]
Pretty sure I broke that in a19ede871d985b642508a4ff35763eb04949af5a your welcome!

**Comment by wltjr** [comment]
I guess that upload stuff for like jtidy.sourceforget.net. Which we will not be using. Not sure about that section. Not sure about creating a github page for the project. If that is even necessary at this time. The current one does not seem to provide much unique information. It would make sense for like online Javadocs or something, but beyond that. Readme, jars under release and uploaded to maven/gradle repos is likely sufficient for now.

**Comment by wltjr** [comment]
I guess there are some useful guides there. Not sure about that stuff. Or it being in pom.xml. Maybe can remove it and deal with site on its own. Usually has its own repo for github pages. Not to familiar with that, haven't set one up yet.

**Comment by dellgreen** [comment]
I agree, its unnecessary/legacy at the moment and should be removed from pom. Maintaining the code/tests and creating successful build with bug fixes should take priority for now.

**Comment by wltjr** [comment]
Feel free to remove what ever. Better than my modifications of breaking stuff. I pretty much skipped Maven, went from Ant to Gradle. I use both minimally. Lets focus on the code and tests for now, and can deal with website and what not later. I can likely help more with the website since I will likely be doing minimal on the coding front.
