### ISSUE TITLE
Bring dependencies up to date

### ISSUE THREAD

**Issue by dellgreen** [jtidy/jtidy#19]
Update dependencies versions so they don't get stuck on older versions and hence break with newer versions of build tools and JDK

**Comment by dellgreen** [comment]
After review no work is required, all dependencies are currently up-to-date

**Comment by wltjr** [comment]
I updated the versions of dependencies in a past revision b8d3728 in the pom.xml at least. I attempted to remove versions d98bcbc, to use the latest. But seems a version is required, so I just went with latest versions. Another thing to maintain over time... Ideally would just set the package, and if a new version broke, update it for that. I understand reasoning for versions as well. Slots would be better, so a package could use the latest version with bug fixes, that is known not to break API, etc. That is how its handled on Gentoo vs versions. Though you can use versions I just prefer slots. Many things if not most do not require a specific version of a library or other.
