### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by crivano** [jtidy/jtidy#24]
Hi, is this project already on Maven Central?

**Comment by dellgreen** [comment]
I think @wltjr is placed to answer this one as he kindly did all the configuration work for this github project. :)

**Comment by wltjr** [comment]
We have not released to Maven Central, but that is possible if there is interest. I created a tag for my needs some time ago. There has been a fair amount of work since. Not sure what version we should go with; deciding on version would likely be the first step. I can look into setting up release integration for auto upload to Maven Central upon tag/release. I think we also need to establish credentials for upload to Maven Central. Then, it will just be a matter of creating a tag.

**Comment by dellgreen** [comment]
I would suggest 1.0.1 as the next logical version that conforms to maven version scheme and continues forward from your original  v1.0 tag. Also Is there a known point in time that we could tag a previous commit with r938 from when it was forked?

**Comment by dellgreen** [comment]
looks like 02059b934e1cb4ddc90d9d136d45eecacc6bbec2 is there commit that we should tag with r938

**Comment by wltjr** [comment]
@dellgreen feel free to create any tags as needed. We need a couple things before maven upload, a Sonatype account and gpg key for the project. I will look into that as soon as possible, time permitting.

**Comment by dellgreen** [comment]
@wltjr thanks for doing this, much appreciated. I have tagged r938 and 1.0.1 in preparation.

**Comment by crivano** [comment]
I seems that GitHub now has an integration with Maven and it is free for open-source projects. But, as far as I can see, it doesn't publish to Maven Central.

https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-apache-maven-for-use-with-github-package-registry

**Comment by crivano** [comment]
@wltjr , thank you very much. JTidy is an important tool and a updated release will be much appreciated!

**Comment by dector** [comment]
I guess until jtidy will be published to Maven Central / Sonatype we can use [Jitpack](https://jitpack.io/#jtidy/jtidy/1.0.1).

**Comment by wltjr** [comment]
Sorry for the delay, I have been really busy and presently working through a backlog. I hope to get to this within a week or two max.

**Comment by wltjr** [comment]
I created the [initial issue OSSRH-53836](https://issues.sonatype.org/browse/OSSRH-53836) in Sonatype's Jira as part of the process for deploying to maven central. I will be working on the other parts while we await their approval or rejection.

@dellgreen, I am not sure if you have a Sonatype Jira account. I added your name, dellgreen to the list of usernames that can publish. I am unsure if that means git username or sonatype jira username. Just a heads up there, so, you can publish as well as I can on tag/commit.

If others here would like to join the project and further the codebase let me know. Presently, there is not really anyone doing active development. There is also a back story on the history I need to publish. A past developer informed me why they ceased further development. Essentially, abandoning the codebase for another. Not to discourage anyone from using or furthering jtidy, just information I need to publish on the readme someday.

**Comment by wltjr** [comment]
All done, it should be deployed now, just waiting for it to show up in maven repo's.

**Comment by wltjr** [comment]
It is live on maven now, https://search.maven.org/artifact/com.github.jtidy/jtidy/1.0.2/jar

**Comment by dellgreen** [comment]
@wltjr great job, well done.

**Comment by crivano** [comment]
Great news! Thank you very much! Not yet in https://mvnrepository.com/, though.

**Comment by wltjr** [comment]
@crivano, that is a third party repository that indexes other repositories. It should pick it up from central or sonatype repositories depending on when mvnrepository.com updates their index.

**Comment by crivano** [comment]
Hi @wltjr , that is great! Thank you!
