### ISSUE TITLE
Html5 docType not supported

### ISSUE THREAD

**Issue by QMG-kazala** [jtidy/jtidy#26]
`<!DOCTYPE>` for HTML5 is this:

`<!DOCTYPE html>`

But jtidy does not recognise it. It reports:

```
InputStream: Doctype given is ""
InputStream: Document content looks like HTML 4.01 Transitional
```

**Comment by dellgreen** [comment]
All pull requests are welcome :)

If you are looking to validate html5 then I would recommend https://mvnrepository.com/artifact/nu.validator/validator
