### ISSUE TITLE
A `java -jar jtidy-1.0.2.jar -v` outputs JTidy released on 2009-12-01

### ISSUE THREAD

**Issue by QMG-kazala** [jtidy/jtidy#28]
A `java -jar jtidy-1.0.2.jar -v` outputs JTidy released on 2009-12-01... maybe that should be 2019... a simple typo probably

**Comment by wltjr** [comment]
Thank you for reporting the issue! It looks like I missed a file, [jtidy.properties](https://github.com/jtidy/jtidy/blob/master/src/main/resources/jtidy.properties), when doing the versioning and release to Maven central. We will have to ensure that is updated along with the pom.xml and sonar-project.properties file for the next release.
