### ISSUE TITLE
Parsing of Unicode code points >U+FFFF does not work

### ISSUE THREAD

**Issue by UweRyssel** [jtidy/jtidy#38]
There is an incompatibility in the handling of Unicode characters inside the implementation of JTidy's lexer:

The method Lexer.addCharToLexer(int c) obviously expects 32-bit Unicode code points, which are internally converted to UTF-8 using EncodingUtils.encodeCharToUTF8Bytes(). However, all calls of Lexer.addCharToLexer use UTF-16 Unicode code units, for example from String.charAt() or Reader.read().

The result is that all Unicode characters >U+FFFF are replaced by two 0xFFFD characters during parsing, since their Unicode code units are recognized as invalid.

**Comment by gaias-jyh** [comment]
sample html with chinese
`<!DOCTYPE html><html><body>南𠖎段</body></html>`
->
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta name="generator" content="HTML Tidy for Java (vers. 2009-12-01), see jtidy.sourceforge.net" /> <title></title> </head> <body> 南段 </body> </html>`
