### ISSUE TITLE
Enable Failing tests to break the build

### ISSUE THREAD

**Issue by dellgreen** [jtidy/jtidy#4]
Currently failing tests do not fail the build. This unfortunately have left the tests in an unusable state as changes have been added. To ensure new changes don't become breaking changes, the build should turn on the failing of the build if any tests fail.

This has a dependency on first fixing the failing tests so that we have reliable suite of tests to program against. [Fix broken tests](https://github.com/jtidy/jtidy/issues/2)

**Comment by haumacher** [comment]
Some test infrastructure problems have been fixed. Remaining test expectations have been adjusted to the status quo. Build now requires that all tests succeed. Fixing anything is not possible with 100 tests failing. Therefore it's better to check whether some other tests that starts failing after fixing something have wrong expectations.
