### ISSUE TITLE
Permission issue while creating a branch

### ISSUE THREAD

**Issue by bhaveshkharwa** [jtidy/jtidy#42]
I have fixed for https://sourceforge.net/p/jtidy/bugs/141/
I created a new branch and trying to push but getting error 403. Is only specific person can push into this repo?

**Comment by dellgreen** [comment]
is your commit currently on a branch of your fork of this repo, if so you just need to create a pull request

**Comment by bhaveshkharwa** [comment]
thanks. Created PR. https://github.com/jtidy/jtidy/pull/43
